-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    "Email" character(20) NOT NULL,
    id integer NOT NULL,
    "Password" character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."SystemEmployees"
(
    id integer NOT NULL,
    "firstName" character varying(100) NOT NULL,
    "lastName" character varying(100) NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employee
(
    id integer NOT NULL,
    "firstName" character varying(100) NOT NULL,
    "lastName" character varying(100) NOT NULL,
    nationalyt_id character varying(11) NOT NULL,
    "birthDate" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    "companyName" character varying(100) NOT NULL,
    "emailAdres" character varying(20) NOT NULL,
    id integer NOT NULL,
    password character varying(20) NOT NULL,
    website character varying(50) NOT NULL,
    phone character varying(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Positions"
(
    "personId" integer NOT NULL,
    id integer NOT NULL,
    "positionName" character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."SystemEmployees"
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employee
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."Positions"
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;

END;
